export const AUTH_COMPLETE_SIGN_UP = 'AUTH_COMPLETE_SIGN_UP';
export const AUTH_INIT = 'AUTH_INIT';
export const AUTH_RESET_PASSWORD = 'AUTH_RESET_PASSWORD';
export const AUTH_SEND_RESET_PASSWORD_CODE = 'AUTH_SEND_RESET_PASSWORD_CODE';
export const AUTH_SET_STATE = 'AUTH_SET_STATE';
export const AUTH_SIGN_IN = 'AUTH_SIGN_IN';
export const AUTH_SIGN_IN_EXTERNAL = 'AUTH_SIGN_IN_EXTERNAL';
export const AUTH_SIGN_OUT = 'AUTH_SIGN_OUT';
export const AUTH_SIGN_UP = 'AUTH_SIGN_UP';
export const AUTH_USERNAME_SIGN_UP = 'AUTH_USERNAME_SIGN_UP';
export const AUTH_VERIFY_USERNAME = 'AUTH_VERIFY_USERNAME';
export const AUTH_UPDATE_USER_ATTRIBUTES = 'AUTH_UPDATE_USER_ATTRIBUTES';
export const AUTH_CHANGE_PASSWORD = 'AUTH_CHANGE_PASSWORD';

export const ERRORS = {
  PASSWORDS_SHOULD_MATCH: 'Passwords should match.',
};
